= SSDD Document Building

This document is built using asciidoctor, not asciidoc.
For asciidoctor description and differences see: 

manpage: https://asciidoctor.org/man/asciidoctor

manual: https://asciidoctor.org/docs/user-manual/

PDF manual: https://asciidoctor.org/docs/asciidoctor-pdf

PDF more: https://github.com/asciidoctor/asciidoctor-pdf

== Quick Start

Prerequisite: docker (or podman) and make is installed.

....
$ make
$ open _build/ssdd/ssdd.pdf
....

Other Makefile options:

**make** - builds SSDD into PDF +
**make pdf** - same as previous +
**make html** - builds SSDD into self-contained html +
**make unpacked** - builds SSDD into HTML but with images in a sub-folder +
**make <filename>.html** - builds file into HTML (see example below) +
**make <filename>.pdf** - builds file into PDF (see exmple below) +

    make scope.html - operates on content/2-scope/scope.adoc
    make glossary.pdf - operates on content/4-appendicies/glossary.adoc

== Two-Layer Directory Hierarchy

To avoid the chaos of manipulating image include paths in every include
file, a two-level directory hierarchy is imposed across the repository
such that all content files have the same include path to the images
folder.

== Images Location

Place all images in `resources/images`.
This is the one and only directory for all images.

== Customizing PDF Output

PDF themes only have an effect on PDF.

https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.0.beta.7/docs/theming-guide.adoc

Although attributes in the document itself could be hard-coded to
specify the PDF theme, we use more flexible command line arguments.

We require our own PDF theme to setup page headers and footers
needed for a compliant SSDD.

== Customizing HTML Output

Skins only have an effect on HTML.

https://github.com/darshandsoni/asciidoctor-skins

https://darshandsoni.com/asciidoctor-skins/screenshots/

https://github.com/asciidoctor/asciidoctor-stylesheet-factory

Using adoc-colony stylesheet from the factory, and modified one
line to center image captions.

Second choice for HTML styling is stylesheet adoc-readthedocs.

Although attributes in the document itself could be hard-coded to
specify the style, we use more flexible command line arguments.

== Source Code Highlighting

Choose a theme from here:

https://github.com/rouge-ruby/rouge/tree/master/lib/rouge/themes

In document set these attributes accordingly:
....
    :source-highlighter: rouge
    :rouge-style: magritte
....
