== System Architectural Design

This chapter describes the technical system that enables the design and
behaviors described in the previous chapter. The hub refresh design
consists of a number of services where each service is the equivalent of
computer software configuration items (CSCI).

All services share some common characteristics. These are presented in
the first few paragraphs. Following that is the presentation of all
services in the system.

=== Services Introduction

Services are the fundamental architectural component in the BFT2
system. A service runs an application or parts of an application. A
service is packaged into a container, usually one service per container.

The benefits of services are numerous and include:

• Distinct teams can work on their own service.
• Teams can deploy a service as frequently as they wish without disrupting other teams.
• Teams scale their service the way they see fit.
• Teams provide monitoring, backups and disaster recovery specific to their service.
• Easier automated testing.
• Rapid and flexible deployment models.
• Higher overall resiliency.

Some services are statefull and use an in-memory database to maintain
state, others have no state but require context information along with
each message. The BFT network makes use of both models where
appropriate, favoring stateless where possible.

=== Three Categories of BFT Services

There are several types of services in use in the BFT system each with
different initializations, monitoring and deployments characteristics.

. Satellite Data Processing (SDP) Service - Service that processes
over-the-air satellite traffic and is written specifically to
participate on the BFT network. A distinguishing attribute of this type
of service is that it requires satellite configuration. An example of
this is a Return Link Physical Layer Processor service.

. Management and Support (MAS) Service - Service that supports BFT
network traffic processing but doesn't itself process satellite
traffic. It is, however, written specifically to participate on the BFT
network. Examples of this are Test Manager, Command Relay service, Error
Handling service.

. Commercial Infrastructure Support (CIS) Service - COTS third party
service that without modification supports the BFT network. Examples of
this are RabbitMQ and Fluentd.

We also distinguish between SDP services that are dedicated to a
particular link and those that can service any link.

• Dedicated service - Service that is assigned exclusively to just one
  link and stays assigned for its lifetime. For example a Return Link
  Physical Layer Processor service is dedicated to process traffic for
  only ReturnLinkId:6.

• Non-dedicated service - Service that can process any link - because
  the service can easily switch state/context, or messages that it
  processes carry enough state/context.
