# ----------------------------------------------
#
# 
# ----------------------------------------------

name: Release
run-name: Trigger release on branch "${{ github.ref_name }}"

on:
  workflow_dispatch: # Manually triggered workflow
    inputs:
      level:
        description: semantic version level to bump
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:

  build-and-release:
    uses: ./.github/workflows/shared-build.yml
    with:
      do-release: true
      release-level: ${{ inputs.level }}
    secrets: inherit  # Pass repository secrets to the shared workflow
