# ----------------------------------------------
#
#
# ----------------------------------------------

name: Shared-Build
run-name: Shared Build on branch "${{ github.ref_name }}" - ${{ github.event.head_commit.message }}

on:
  
  workflow_call:
    inputs:
      do-release:
        description: Should we perform a release in addition to a build
        required: true
        type: string
        
permissions:
  contents: write
  
jobs:

  shared-build:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install podman
        run:  echo sudo apt install -y podman
        
      - name: lookee lookee
        run: |
          echo "event name: ${{ github.event_name }}"
          echo "action: ${{ github.action }}"
          echo "event commit msg: ${{ github.event.head_commit.message }}"
          echo "event pull_request title: ${{ github.event.pull_request.title }}"
          title="${{ github.event.pull_request.title }}"
          if [ -z "$title" ]; then
              echo "title is empty"
          else
              echo "title is $title"
          fi
          if [[ $title =~ ^"Release:" ]]; then
              echo "starts with Release:"
          else
              echo "does NOT start with Release:"
          fi
          if ${{ github.event.pull_request.merged == true }}; then
              echo "pull_request was merged"
          else
              echo "pull_request was NOT merged"
          fi
          echo "howie ${{ inputs.do-release }}"
          if  ${{ inputs.do-release }}; then
              echo "do-release is true"
          else
              echo "do-release is false"
          fi
              

      - name: Run unit tests
        run:  |
          echo make unit-test

      - name: Bump version number (release-only)
        if: ${{ inputs.do-release }}
        run:  |
          bump_level= ${{ steps.build_type.outputs.bump_level }}
          echo make BUMP=$bump_level bump-version

      - name: Build docs
        run:  echo make docs

      - name: Publish docs
        run:  echo make docs-publish

      - name: Create changelog (release-only)
        if: ${{ steps.build_type.outputs.do_release == 'yes' }}
        run: echo make update-changelog

      - name: Create tarball
        id: version_info
        run: |
          echo make create-tarball
          
#          triplet=$(cat version)
#          libName=$(cat _build/release/lib-name)
#          tarFile=$(cat _build/release/tarfile-name)
#          tarFileBase=$(basename $tarFile)
#          tagName=v$triplet
#          echo "triplet=$triplet"          >> ${GITHUB_OUTPUT}
#          echo "libName=$libName"          >> ${GITHUB_OUTPUT}
#          echo "tarFile=$tarFile"          >> ${GITHUB_OUTPUT}
#          echo "tarFileBase=$tarFileBase"  >> ${GITHUB_OUTPUT}
#          echo "tagName=v$triplet"         >> ${GITHUB_OUTPUT}
#
      - name: Test tarball
        run:  echo make test-tarball
        
      - name: Checkin docs (release-only)
        if: ${{ steps.build_type.outputs.do_release == 'yes' }}
        # Performs a checkin on docs, version file and changelog file.
        # Hence we need the paths-ignore specification
        # at top of this action to prevent a build loop. 
        # Plus needs "contents" permission to write to repo.
        run: |
          echo git config user.name  github-actions[bot]
          echo git config user.email github-actions[bot]@users.noreply.github.com
          echo git add -A docs/site version etc/changelog.md
          echo git commit -m "Release ${{ steps.version_info.outputs.tagName }}"
          echo git push

      - name: Push tarball to Github Release (release-only)
        if: ${{ steps.build_type.outputs.do_release == 'yes' }}
        run: echo Invoking release action
        
#        uses: softprops/action-gh-release@v2
#        with:
#          files: ${{ steps.version_info.outputs.tarFile }}
#          name:  ${{ steps.version_info.outputs.tagName }}
#          tag_name: ${{ steps.version_info.outputs.tagName }}
#          body: Download ${{ steps.version_info.outputs.tarFileBase }}
#          draft: false
#          prerelease: false
#
      - name: Deploy release docs
        if: ${{ steps.build_type.outputs.do_release == 'yes' }}
        uses: ./.github/workflows/deploy-gh-pages.yml
